[package]
name = "shoes"
version = "0.1.3"
edition = "2021"
license = "MIT"
description = "A multi-protocol proxy server."
homepage = "https://github.com/cfal/shoes/"
repository = "https://github.com/cfal/shoes/"
readme = "README.md"
keywords = ["proxy", "proxy-server", "shadowsocks", "v2ray", "vmess"]
categories = ["command-line-utilities", "network-programming"]

[dependencies]
aes = "0.8.4"
argon2 = "0.5.3"
async-trait = "0.1.83"
base64 = "0.22.1"
blake3 = "1.5.5"
cfb-mode = "0.8.2"
digest = "0.10.7"
env_logger = "0.11.5"
futures = "0.3.31"
hmac = "0.12.1"
log = "0.4.22"
md-5 = "0.10.6"
memchr = "2.7.4"
notify = "7.0.0"
parking_lot = "0.12.3"
percent-encoding = "2.3.1"
quinn = "0.11.6"
rand = "0.8.5"
ring = "0.17.8"
rustls = { version = "0.23.19", default-features = false, features = ["ring"] }
sha2 = "0.10.8"
sha3 = "0.10.8"
serde = { version = "1.0.215", features = ["derive", "std"] }
serde_yaml = "0.9.34"
tokio = { version = "1.42.0", features = [
    "fs",
    "io-util",
    "macros",
    "net",
    "rt-multi-thread",
    "sync",
    "time",
] }
tokio-rustls = { version = "0.26.1", default-features = false, features = ["logging", "tls12", "ring"] }
webpki-roots = { version = "0.26.7" }

[profile.release]
opt-level = 3
lto = "fat"
strip = true
